# Generated by Django 6.0.1 on 2026-02-02 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="项目名称")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("parameters", models.JSONField(default=dict, verbose_name="模型参数")),
                (
                    "stl_file",
                    models.FileField(
                        blank=True,
                        upload_to="generated_models/",
                        verbose_name="模型文件",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True, upload_to="previews/", verbose_name="预览图"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("generating", "生成中"),
                            ("completed", "已完成"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="项目描述")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "设计项目",
                "verbose_name_plural": "设计项目",
                "ordering": ["-created_at"],
            },
        ),
    ]
